### ISSUE TITLE
LaTeX PDF: drop Arial and use Helvetica?

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.meeting#13]
The Arial font is not in the default LaTeX distribution and needs to be installed separately on the OS.
Therefore we should maybe drop it and use Helvetica.

See [layout.tex](https://github.com/4teamwork/ftw.meeting/blob/86ab9d925cc99dea9dd0782b8b3a82916db817ee/ftw/meeting/latex/templates/layout.tex#L13)

**Comment by maethu** [comment]
ftw.meeting is deprecated - no work is gonna happen here anymore.
